[package]
name = "vkteams-bot"
version = "0.2.2"
edition = "2021"
authors = ["Andrei G. <k05h31@gmail.com>"]
description = "VK Teams Bot API client"
license = "MIT"
repository = "https://github.com/k05h31/vkteams-bot/tree/master"
readme = "README.md"
keywords = ["vk", "teams", "bot", "api", "client"]
categories = ["asynchronous", "api-bindings", "web-programming::http-client"]

[dependencies]

reqwest = { version = "0.11.22", features = ["json", "stream", "multipart"] }
tokio = { version = "1.35.0", features = ["full"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
log = "0.4.20"
dotenvy = "0.15.7"
anyhow = "1.0.75"
pretty_env_logger = "0.5.0"
serde_url_params = "0.2.1"
tokio-util = { version = "0.7", features = ["codec"] }
futures = "0.3"
