[package]
license = "MIT OR Apache-2.0"
name = "vkteams-bot"
version = "0.7.0"
edition = "2024"
authors = ["Andrei G. <k05h31@gmail.com>"]
description = "VK Teams Bot API client"
repository = "https://github.com/bug-ops/vkteams-bot/tree/master"
readme = "README.md"
keywords = ["vk", "teams", "bot", "api", "client"]
categories = ["asynchronous", "api-bindings", "web-programming::http-client"]

[dependencies]
reqwest = { version = "0.12", features = ["json", "stream", "multipart"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
tower-http = { version = "0.6", features = [
    "timeout",
    "trace",
    "limit",
    "cors",
], optional = true }
async-trait = { version = "0.1", optional = true }
axum = { version = "0.8", features = ["macros", "http2"], optional = true }
serde = { version = "1", features = ["derive"] }
serde_url_params = "0.2"
serde_json = "1"
log = "0.4"
tera = { version = "1", default-features = false, optional = true }
tonic-health = { version = "0.13", optional = true }
paste = "1"
url = "2.5"

[features]
default = ["longpoll"]
full = ["webhook", "longpoll", "templates", "grpc"]
longpoll = []
webhook = ["dep:axum", "dep:tower-http", "dep:async-trait"]
templates = ["dep:tera"]
grpc = ["dep:tonic-health"]

[dev-dependencies]
vkteams-bot = { version = "0.7", path = ".", features = ["full"] }
tonic = "0.13"
dotenvy = "0.15"
pretty_env_logger = "0.5"
