[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2024"
repository = "https://github.com/bug-ops/vkteams-bot/tree/master"
readme = "README.md"
