[package]
license = "MIT OR Apache-2.0"
name = "vkteams-bot-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
