[graph]
targets = ["x86_64-unknown-linux-musl"]
all-features = false
no-default-features = true

[output]
feature-depth = 1

[advisories]
ignore = [{ id = "RUSTSEC-2024-0436", reason = "Not critical" }]

[licenses]
allow = [
    "MIT",
    "MPL-2.0",
    "Apache-2.0",
    "Unicode-3.0",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
]
confidence-threshold = 0.8
exceptions = []

[licenses.private]
ignore = true
registries = []

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "deny"
required-git-spec = "tag"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
private = []
[sources.allow-org]
github = []
gitlab = []
bitbucket = []
