[package]
name = "vkteams-bot-mcp"
version = "0.1.0"
authors = ["Andrei G. <k05h31@gmail.com>"]
description = "VK Teams Bot API MCP"
keywords = ["vk", "teams", "bot", "mcp"]
categories = [
    "asynchronous",
    "api-bindings",
    "web-programming::http-client",
    "mcp",
]
license.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true

[[bin]]
name = "vkteams-bot-mcp"
path = "src/main.rs"

[dependencies]
thiserror = "2"
rmcp = { version = "0.1", features = ["server", "macros", "transport-io"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
schemars = "0.8"
anyhow = "1"
async-trait = "0.1"
vkteams-bot = { path = "../vkteams-bot" }
