[package]
name = "vkteams-bot-macros"
version = "0.1.0"
description = "VK Teams Bot Macros"

rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
